### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Jhoneagle** [ViliLipo/otm-harjoitustyo#1]
ladattu 10:49, 3.5.2018

- Koodin laatu on monilta osin hyvä. Joidenkin kohtien ymmärtäminen hieman vaikeaa monimutkaisten toimintojen vuoksi. Javadoc auttaisi paljon luokkien ja metodien ymmärtämisessä. 
- Luokkien nimentä on dao-paketissa hieman turhan monimutkainen johtuen "sqlite3" nimi päätteistä. Nimentää voisi selkeyttää muuttamalla varsinaisten dao luokkien nimet. Esimerkiksi "FoodItemDaoSqlite3" vosii olla "FoodItemSql". Tällöin ne kuitenkin erottuisivat ja kertoisivat tarkoituksensa. 
- Testit menevät pääasiallisesti läpi. Kuitenkin UserTest ja MealTest sisältävät joitakin testejä, jotka eivät suostu toimimaan. Koodin paketointi ei myöskään onnistu testien vuoksi.
- Testejä voisi myös nopeuttaa poistamalla kaikki ylimääräiset tulosteet myös logiin tapahtuvat tulosteet. Testejä suorittaessa näitä näyttää olevan hyvinkin paljon. 
- Toiminnallisuutta on hyvin ja monipuolisesti ja täyttävät hyvin vaatimusmäärittelyn.
- Käyttöliittymä on käytännöllinen. Ruoka historia listausta voisi kuitenkin muuttaa niin, että käyttäjä ei saa pop up -ikkunaa joka kerta, kun painaa jotakin kohtaa. Sen sijaan käyttäjä voisi painaa "lisätietoja" painiketta halutessaan pop up -ikkunan.

**Comment by ViliLipo** [comment]
Kiitos palautteesta! Lisäsin loppupalautukseen ehdottamasi nappulan.
